//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zajezdnia_Tramwajowa
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Maszynista
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Maszynista()
        {
            this.Przejazd = new HashSet<Przejazd>();
        }
    
        public int IDMaszynisty { get; set; }

        [Required(ErrorMessage ="Stawka musi byæ podana")]
        public decimal Stawka { get; set; }
        [Required(ErrorMessage = "Imie musi byæ podane")]
        [MinLength(3, ErrorMessage = "Imie musi mieæ minimalnie 3 litery")]
        [MaxLength(20, ErrorMessage = "Imie musi mieæ minimalnie 20 liter")]
        public string Imie { get; set; }
        [Required(ErrorMessage = "Nazwisko musi byæ podane")]
        public string Nazwisko { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Przejazd> Przejazd { get; set; }
    }
}
