//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zajezdnia_Tramwajowa
{
    using System;
    using System.Collections.Generic;
    
    public partial class Przystanek
    {
        public int IDPrzystanku { get; set; }
        public int IDTrasy { get; set; }
        public string NazwaPrzystanku { get; set; }
        public byte[] RowVersion { get; set; }
    
        public virtual Trasa Trasa { get; set; }
    }
}
