//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zajezdnia_Tramwajowa
{
    using System;
    using System.Collections.Generic;
    
    public partial class uzyciePrzystankow
    {
        public string NazwaPrzystanku { get; set; }
        public Nullable<int> Ilosc_Przejazdow { get; set; }
    }
}
